### ISSUE TITLE
What are the parameters?

### ISSUE THREAD

**Issue by derekmartinjs** [daveshap/CoverLetterGenerator#1]
Great idea here Dave! Working on a Siri Shortcut that will make this even easier to use.

What were the parameters that rendered the best outputs? 

![IMG_E01CA0158606-1](https://user-images.githubusercontent.com/59883894/190528929-faa0b3fc-67c8-42b3-8c74-bcad3e51b827.jpeg)

**Comment by daveshap** [comment]
Default parameters
